// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/list-loan-requests.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";
var mockRequests = [
  { id: 1, senderName: "Kaia Lunde", senderAvatar: "KL", amount: 2e3, repaymentPeriod: "28 March 2025", interestPercent: 5, message: "Hope this helps \u{1F60A}", status: "Pending", receivedAt: "Today" },
  { id: 2, senderName: "Erik Johansen", senderAvatar: "EJ", amount: 4e3, repaymentPeriod: "15 April 2025", interestPercent: 3, message: "Need it for rent this month, will pay back ASAP.", status: "Pending", receivedAt: "Yesterday" },
  { id: 3, senderName: "Anna Kristoffersen", senderAvatar: "AK", amount: 1500, repaymentPeriod: "10 April 2025", interestPercent: 0, message: "Thanks in advance!", status: "Pending", receivedAt: "2 days ago" }
];
var list_loan_requests_default = defineTool({
  name: "list_loan_requests",
  title: "List loan requests",
  description: "List all incoming loan requests from the Pengio demo dataset.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(mockRequests, null, 2) }],
    structuredContent: { requests: mockRequests }
  })
});

// src/lib/mcp/tools/list-loan-offers.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";
var mockLoanOffers = [
  { id: 101, senderName: "Jenny", senderAvatar: "JN", amount: 1e3, repaymentPeriod: "28 March 2025", interestPercent: 5, message: "Hope this helps \u{1F60A}", condition: "", status: "Pending", receivedAt: "Today" }
];
var list_loan_offers_default = defineTool2({
  name: "list_loan_offers",
  title: "List loan offers",
  description: "List all incoming loan offers from the Pengio demo dataset.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(mockLoanOffers, null, 2) }],
    structuredContent: { offers: mockLoanOffers }
  })
});

// src/lib/mcp/tools/list-contacts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";
var contacts = [
  { id: 1, name: "Anna Kristoffersen", avatar: "AK", phone: "+47 912 34 567", email: "anna@test.com" },
  { id: 2, name: "Erik Johansen", avatar: "EJ", phone: "+47 987 65 432", email: "erik@test.com" },
  { id: 3, name: "Lydia Bergson", avatar: "LB", phone: "+47 923 45 678" },
  { id: 4, name: "Cristofer Dias", avatar: "CD", phone: "+47 934 56 789" },
  { id: 5, name: "Miracle Saris", avatar: "MS", phone: "+47 945 67 890" }
];
var list_contacts_default = defineTool3({
  name: "list_contacts",
  title: "List contacts",
  description: "List all Pengio demo contacts available for lending or borrowing.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contacts, null, 2) }],
    structuredContent: { contacts }
  })
});

// src/lib/mcp/tools/get-loan-request.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z } from "npm:zod@^4.4.3";
var mockRequests2 = [
  { id: 1, senderName: "Kaia Lunde", senderAvatar: "KL", amount: 2e3, repaymentPeriod: "28 March 2025", interestPercent: 5, message: "Hope this helps \u{1F60A}", status: "Pending", receivedAt: "Today" },
  { id: 2, senderName: "Erik Johansen", senderAvatar: "EJ", amount: 4e3, repaymentPeriod: "15 April 2025", interestPercent: 3, message: "Need it for rent this month, will pay back ASAP.", status: "Pending", receivedAt: "Yesterday" },
  { id: 3, senderName: "Anna Kristoffersen", senderAvatar: "AK", amount: 1500, repaymentPeriod: "10 April 2025", interestPercent: 0, message: "Thanks in advance!", status: "Pending", receivedAt: "2 days ago" }
];
var get_loan_request_default = defineTool4({
  name: "get_loan_request",
  title: "Get loan request",
  description: "Get a single loan request by its numeric id.",
  inputSchema: { id: z.number().int().describe("Loan request id") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const req = mockRequests2.find((r) => r.id === id);
    if (!req) return { content: [{ type: "text", text: `No loan request with id ${id}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(req, null, 2) }],
      structuredContent: { request: req }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "pengio-first-steps",
  title: "Pengio: First Steps",
  version: "0.1.0",
  instructions: "Read-only tools that expose Pengio's demo lending dataset: loan requests, loan offers, and contacts. All data is mock/demo data \u2014 nothing is persisted.",
  tools: [list_loan_requests_default, list_loan_offers_default, list_contacts_default, get_loan_request_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
